'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const vm=require('vm');
const pack=require('../assets/v10-noses');
const compatibility=require('../assets/v10-nose-compatibility');
const placements=require('../assets/v10-nose-placements');
const v10Heads=require('../assets/v10-heads');
const ROOT=path.resolve(__dirname,'..');
const OUT=path.join(ROOT,'generated','qa','v10-noses');
const BACKGROUNDS={cream:'#efe2c8',white:'#fffdf5',black:'#171512',transparent:null};
const inkFor=background=>background==='black'?'#f4e7ca':'#171512';
const inner=svg=>svg.replace(/^\s*<svg[^>]*>/,'').replace(/<\/svg>\s*$/,'');
function prefix(svg,scope){let out=svg;for(const id of [...svg.matchAll(/id=['"]([^'"]+)['"]/g)].map(m=>m[1]))out=out.replaceAll(`id='${id}'`,`id='${scope}-${id}'`).replaceAll(`id="${id}"`,`id="${scope}-${id}"`).replaceAll(`url(#${id})`,`url(#${scope}-${id})`);return out;}
function baselineBases(){const context={window:{MONSTER_PARTS:{}},console};vm.createContext(context);for(const file of ['assets/parts/bases.js','assets/library-v9/bases.js','assets/hero-v9/bases.js'])vm.runInContext(fs.readFileSync(path.join(ROOT,file),'utf8'),context,{filename:file});return context.window.MONSTER_PARTS.bases;}
const bases=new Map([...baselineBases(),...v10Heads.assets].map(item=>[item.id,item]));
const assets=new Map(pack.assets.map(item=>[item.id,item]));
function transform(value){const x=(value.x||0)*600,y=(value.y||0)*600,s=value.scale||1,r=value.rotation||0;return `translate(${x} ${y}) translate(300 300) rotate(${r}) scale(${s}) translate(-300 -300)`;}
function digest(){const hash=crypto.createHash('sha256');for(const file of ['assets/v10-nose-assets-01.js','assets/v10-nose-assets-02.js','assets/v10-noses.js','assets/v10-nose-compatibility.js','assets/v10-nose-placements.js'])hash.update(fs.readFileSync(path.join(ROOT,file)));return hash.digest('hex');}
function report(){const errors=[];for(const asset of pack.assets){const [x,y,w,h]=asset.bounds;if(x<18||y<250||x+w>582||y+h>472)errors.push(`${asset.id} escapes the shared nose-safe region`);if(!compatibility[asset.id]?.approved?.length)errors.push(`${asset.id} has no approved base`);if(!Object.keys(placements).some(key=>key.endsWith(`|${asset.id}`)))errors.push(`${asset.id} has no integration fixture`);}for(const [key,value] of Object.entries(placements)){const [baseId,noseId]=key.split('|');if(!bases.has(baseId))errors.push(`${key} references an unknown base`);if(!assets.has(noseId))errors.push(`${key} references an unknown nose`);if(!compatibility[noseId]?.approved?.includes(baseId))errors.push(`${key} is not an approved pairing`);if(Math.abs(value.x)>0.04||Math.abs(value.y)>0.04||value.scale<0.8||value.scale>1.05||Math.abs(value.rotation)>5)errors.push(`${key} exceeds rigid-placement limits`);}return {schemaVersion:'1.0.0',issue:42,revision:pack.revision,status:errors.length?'failed':'passed',humanApprovalRequired:true,runtimeGeometry:false,generatedAt:'1970-01-01T00:00:00.000Z',sourceDigest:digest(),baselineCount:pack.baselineCount,candidateCount:pack.assets.length,totalCount:pack.baselineCount+pack.assets.length,targetCount:pack.targetCount,familyCount:new Set(pack.assets.map(item=>item.family)).size,classifiedBasePairs:Object.values(compatibility).reduce((sum,item)=>sum+item.approved.length+item.acceptable.length+item.blocked.length,0),approvedPairCount:Object.values(compatibility).reduce((sum,item)=>sum+item.approved.length,0),rigidOverrideCount:Object.keys(placements).length,review:{backgrounds:pack.reviewBackgrounds,states:pack.reviewStates,scales:pack.reviewScales},errors};}
function card(pairKey,index,background){const [baseId,noseId]=pairKey.split('|'),base=bases.get(baseId),nose=assets.get(noseId),override=placements[pairKey],col=index%3,row=Math.floor(index/3),x=col*410,y=row*360,ink=inkFor(background),scope=`${background}-${index}`;const baseSvg=prefix(inner(base.svg),`${scope}-base`),noseSvg=prefix(inner(nose.svg),`${scope}-nose`),scene=`<g transform='translate(${x+55} ${y+38}) scale(.48)'><g opacity='.52'>${baseSvg}</g><g transform='${transform(override)}'>${noseSvg}</g></g>`;const flip=`<g transform='translate(${x+346} ${y+38}) scale(-.24 .24)'><g opacity='.42'>${baseSvg}</g><g transform='${transform(override)}'>${noseSvg}</g></g>`;const thumb96=`<g transform='translate(${x+280} ${y+232}) scale(.16)'>${noseSvg}</g>`,thumb48=`<g transform='translate(${x+368} ${y+256}) scale(.08)'>${noseSvg}</g>`;return `<g>${scene}${flip}${thumb96}${thumb48}<rect x='${x+18}' y='${y+18}' width='374' height='322' rx='16' fill='none' stroke='${ink}' stroke-opacity='.25'/><text x='${x+28}' y='${y+307}' fill='${ink}' font-family='Arial,sans-serif' font-size='14' font-weight='700'>${nose.name}</text><text x='${x+28}' y='${y+327}' fill='${ink}' opacity='.65' font-family='monospace' font-size='10'>${pairKey}</text><text x='${x+274}' y='${y+327}' fill='${ink}' opacity='.65' font-family='monospace' font-size='10'>96 / 48 px</text></g>`;}
function sheet(background){const fill=BACKGROUNDS[background],ink=inkFor(background),pairs=Object.keys(placements).sort();return `<svg xmlns='http://www.w3.org/2000/svg' width='1230' height='2260' viewBox='0 0 1230 2260'>${fill?`<rect width='1230' height='2260' fill='${fill}'/>`:''}<text x='28' y='42' fill='${ink}' font-family='Arial,sans-serif' font-size='25' font-weight='800'>V10 NOSE / SNOUT CANDIDATES — ${background.toUpperCase()}</text><text x='28' y='67' fill='${ink}' opacity='.68' font-family='monospace' font-size='12'>authored pair · flipped pair · 96 px · 48 px · pending human art-direction approval</text><g transform='translate(0 74)'>${pairs.map((key,index)=>card(key,index,background)).join('')}</g></svg>`;}
async function write(){fs.mkdirSync(OUT,{recursive:true});const sharp=require('sharp');for(const background of pack.reviewBackgrounds){const svg=sheet(background),svgPath=path.join(OUT,`integration-${background}.svg`),pngPath=path.join(OUT,`integration-${background}.png`);fs.writeFileSync(svgPath,svg);await sharp(Buffer.from(svg)).png().toFile(pngPath);}fs.writeFileSync(path.join(OUT,'validation-report.json'),JSON.stringify(report(),null,2)+'\n');fs.copyFileSync(path.join(ROOT,'schemas','v10-nose-validation-report.schema.json'),path.join(OUT,'validation-report.schema.json'));}
const result=report();if(result.errors.length){console.error(result.errors.join('\n'));process.exitCode=1;}else if(process.argv.includes('--write'))write().then(()=>console.log(`Wrote V10 nose QA to ${path.relative(ROOT,OUT)}`)).catch(error=>{console.error(error);process.exitCode=1;});else console.log(`V10 nose QA passed: ${result.candidateCount} candidates, ${result.rigidOverrideCount} integration fixtures, ${result.approvedPairCount} approved pairs.`);
